/**
 * Initial Canvas Objects
 * Default objects shown on canvas load for demonstration
 */

import { CanvasObject } from "../types";
import { getRandomVideoUrl } from "../utils/objectFactory";

export const INITIAL_OBJECTS: CanvasObject[] = [
  // Row 1: Human Canvas Natives (Text, Shape, Doodle, Sticky, Link, PDF)
  {
    id: "1",
    type: "text",
    name: "Text",
    x: 100,
    y: 120,
    width: 280,
    height: 120,
    content: "The quick brown fox jumps over the lazy dog. This is a longer paragraph of text that demonstrates how text elements can contain multiple sentences and wrap naturally across multiple lines.",
    state: "idle",
    metadata: { createdAt: Date.now(), updatedAt: Date.now() },
  } as CanvasObject,
  {
    id: "2a",
    type: "shape",
    name: "Circle",
    x: 410,
    y: 100,
    width: 140,
    height: 140,
    shapeType: "circle",
    fillColor: "#ef4444",
    state: "idle",
    metadata: { createdAt: Date.now(), updatedAt: Date.now() },
  } as CanvasObject,
  {
    id: "2b",
    type: "shape",
    name: "Rectangle",
    x: 480,
    y: 140,
    width: 140,
    height: 140,
    shapeType: "rectangle",
    fillColor: "#6366f1",
    state: "idle",
    metadata: { createdAt: Date.now(), updatedAt: Date.now() },
  } as CanvasObject,
  {
    id: "3",
    type: "doodle",
    name: "Doodle",
    x: 650,
    y: 120,
    width: 180,
    height: 120,
    paths:
      "M 20 90 Q 40 20, 80 40 M 70 130 Q 100 80, 150 120 Q 120 100, 80 120 Z",
    strokeColor: "#000000",
    strokeWidth: 2.5,
    state: "idle",
    metadata: { createdAt: Date.now(), updatedAt: Date.now() },
  } as CanvasObject,
  {
    id: "4",
    type: "sticky",
    name: "Sticky",
    x: 860,
    y: 100,
    width: 250,
    height: 180,
    noteColor: "#fef08a",
    noteTitle: "Note Title",
    noteAuthor: "@Oskar",
    content:
      "Can we try a bit more motion blur here...Something like the Wong Kai wei film",
    state: "idle",
    metadata: { createdAt: Date.now(), updatedAt: Date.now() },
  } as CanvasObject,
  {
    id: "5",
    type: "link",
    name: "Link",
    x: 1140,
    y: 100,
    width: 340,
    height: 240,
    url: "https://mouthwash.studio/project/nike-after-dark/",
    title: "Nike After Dark",
    description: "Six cities, 10,000+ runners, one iconic moment.",
    thumbnail: "https://cdn.sanity.io/images/ew1yzffi/production/eeab02a78a73bc6a9d8506132e12d6f57af9f1ca-1200x630.jpg?w=1200&auto=format",
    state: "idle",
    metadata: { createdAt: Date.now(), updatedAt: Date.now() },
  } as CanvasObject,
  {
    id: "6",
    type: "pdf",
    name: "PDF",
    x: 1510,
    y: 100,
    width: 200,
    height: 280,
    fileUrl: "",
    fileName: "document.pdf",
    state: "idle",
    metadata: { createdAt: Date.now(), updatedAt: Date.now() },
  } as CanvasObject,

  // Row 2: AI Artifacts (Image, Video, Audio, Document)
  {
    id: "7",
    type: "image",
    name: "Image",
    x: 100,
    y: 420,
    width: 250,
    height: 200,
    content:
      "https://cdn.midjourney.com/c06a44a1-490a-4473-b458-3ff04e60fbba/0_0.png",
    state: "idle",
    metadata: { 
      createdAt: Date.now(), 
      updatedAt: Date.now(),
      createdBy: { type: "model", name: "Ray3" }
    },
  } as CanvasObject,
  {
    id: "8",
    type: "video",
    name: "Video",
    x: 380,
    y: 420,
    width: 280,
    height: 160,
    content: getRandomVideoUrl(),
    duration: 5,
    state: "idle",
    metadata: { 
      createdAt: Date.now(), 
      updatedAt: Date.now(),
      createdBy: { type: "uploaded" }
    },
  } as CanvasObject,
  {
    id: "8b",
    type: "video",
    name: "Video with Audio",
    x: 690,
    y: 420,
    width: 280,
    height: 160,
    content: "https://storage.cdn-luma.com/dream-machine/b6e2d57d-2b69-441f-ae38-b439894b1337/b4984051-f8b5-423b-a909-4977699fb19d/video_adb1deb67f5f40199d322d99e4ad764b.mp4",
    duration: 5,
    hasAudio: true,
    state: "idle",
    metadata: { 
      createdAt: Date.now(), 
      updatedAt: Date.now(),
      createdBy: { type: "model", name: "Luma Dream Machine" }
    },
  } as CanvasObject,
  {
    id: "9",
    type: "audio",
    name: "Audio",
    x: 1000,
    y: 420,
    width: 250,
    height: 100,
    content: "",
    state: "idle",
    metadata: { 
      createdAt: Date.now(), 
      updatedAt: Date.now(),
      createdBy: { type: "model", name: "Eleven Labs" }
    },
  } as CanvasObject,
  {
    id: "10",
    type: "document",
    name: "Document",
    x: 1280,
    y: 420,
    width: 280,
    height: 300,
    content:
      "This is an AI-generated document with rich content. It can contain paragraphs, formatting, and more.",
    state: "idle",
    labelBgColor: "green",
    metadata: { 
      createdAt: Date.now(), 
      updatedAt: Date.now(),
      createdBy: { type: "user", name: "Jon" }
    },
  } as CanvasObject,
  
  // Test generating state
  {
    id: "11",
    type: "image",
    name: "Generating Image",
    x: 1590,
    y: 420,
    width: 280,
    height: 200,
    content: "",
    state: "generating",
    metadata: { 
      createdAt: Date.now(), 
      updatedAt: Date.now(),
      progress: 45
    },
  } as CanvasObject,

  // Test autolayout grid frame (Row 3)
  {
    id: "frame-1",
    type: "frame",
    name: "Image Grid",
    x: 100,
    y: 800,
    width: 1312, // Width for 5 items: (250 * 5) + (10 * 4) + (10 * 2) + 2 (border) = 1312
    height: 432, // Height for 2 rows: (200 * 2) + (10 * 1) + (10 * 2) + 2 (border) = 432
    createdBy: "human",
    autoLayout: true,
    layout: "grid",
    padding: 10,
    gap: 10,
    children: ["grid-img-1", "grid-img-2", "grid-img-3", "grid-img-4", "grid-img-5", "grid-img-6", "grid-img-7", "grid-img-8"],
    backgroundColor: "#f0f0f0",
    borderRadius: 10,
    state: "idle",
    metadata: { 
      createdAt: Date.now(), 
      updatedAt: Date.now()
    },
  } as CanvasObject,

  // Grid frame children - 8 image placeholders
  {
    id: "grid-img-1",
    type: "image",
    name: "Grid Image 1",
    x: 110, // Will be positioned by autolayout
    y: 810,
    width: 250,
    height: 200,
    content: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&fit=crop",
    parentId: "frame-1",
    state: "idle",
    metadata: { createdAt: Date.now(), updatedAt: Date.now() },
  } as CanvasObject,
  {
    id: "grid-img-2",
    type: "image",
    name: "Grid Image 2",
    x: 370,
    y: 810,
    width: 250,
    height: 200,
    content: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=400&h=300&fit=crop",
    parentId: "frame-1",
    state: "idle",
    metadata: { createdAt: Date.now(), updatedAt: Date.now() },
  } as CanvasObject,
  {
    id: "grid-img-3",
    type: "image",
    name: "Grid Image 3",
    x: 630,
    y: 810,
    width: 250,
    height: 200,
    content: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=400&h=300&fit=crop",
    parentId: "frame-1",
    state: "idle",
    metadata: { createdAt: Date.now(), updatedAt: Date.now() },
  } as CanvasObject,
  {
    id: "grid-img-4",
    type: "image",
    name: "Grid Image 4",
    x: 890,
    y: 810,
    width: 250,
    height: 200,
    content: "https://images.unsplash.com/photo-1426604966848-d7adac402bff?w=400&h=300&fit=crop",
    parentId: "frame-1",
    state: "idle",
    metadata: { createdAt: Date.now(), updatedAt: Date.now() },
  } as CanvasObject,
  {
    id: "grid-img-5",
    type: "image",
    name: "Grid Image 5",
    x: 1150,
    y: 810,
    width: 250,
    height: 200,
    content: "https://images.unsplash.com/photo-1511884642898-4c92249e20b6?w=400&h=300&fit=crop",
    parentId: "frame-1",
    state: "idle",
    metadata: { createdAt: Date.now(), updatedAt: Date.now() },
  } as CanvasObject,
  {
    id: "grid-img-6",
    type: "image",
    name: "Grid Image 6",
    x: 110,
    y: 1020,
    width: 250,
    height: 200,
    content: "https://images.unsplash.com/photo-1475924156734-496f6cac6ec1?w=400&h=300&fit=crop",
    parentId: "frame-1",
    state: "idle",
    metadata: { createdAt: Date.now(), updatedAt: Date.now() },
  } as CanvasObject,
  {
    id: "grid-img-7",
    type: "image",
    name: "Grid Image 7",
    x: 370,
    y: 1020,
    width: 250,
    height: 200,
    content: "https://images.unsplash.com/photo-1472214103451-9374bd1c798e?w=400&h=300&fit=crop",
    parentId: "frame-1",
    state: "idle",
    metadata: { createdAt: Date.now(), updatedAt: Date.now() },
  } as CanvasObject,
  {
    id: "grid-img-8",
    type: "image",
    name: "Grid Image 8",
    x: 630,
    y: 1020,
    width: 250,
    height: 200,
    content: "https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=400&h=300&fit=crop",
    parentId: "frame-1",
    state: "idle",
    metadata: { createdAt: Date.now(), updatedAt: Date.now() },
  } as CanvasObject,
];

